services:
  - type: web
    name: smartkalvi
    env: python
    buildCommand: |
      pip install -U pip setuptools wheel
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
