services:
  - type: web
    name: ai-exam-platform
    env: python
    plan: free
    buildCommand: pip install -U pip setuptools wheel && pip install -r requirements.txt
    startCommand: gunicorn app:app
